force_refresh:
  name: Force Refresh
  description: Recompute the charging plan immediately.
  fields:
    entry_id:
      name: Entry ID
      description: Optional – required only when multiple Smart Charger entries exist.
      example: 1234567890abcdef1234567890abcdef
      selector:
        text:

start_charging:
  name: Start Charging
  description: Turn the selected charger on regardless of the current schedule.
  fields:
    entry_id:
      name: Entry ID
      description: Optional - required only when multiple Smart Charger entries exist.
      example: 1234567890abcdef1234567890abcdef
      selector:
        text:
    entity_id:
      description: Charger switch entity (leave empty to start all chargers).
      example: switch.bedroom_phone_charger
      selector:
        entity:
          domain: switch

stop_charging:
  name: Stop Charging
  description: Turn the selected charger off.
  fields:
    entry_id:
      name: Entry ID
      description: Optional – required only when multiple Smart Charger entries exist.
      example: 1234567890abcdef1234567890abcdef
      selector:
        text:
    entity_id:
      description: Charger switch entity (leave empty to stop all chargers).
      example: switch.bedroom_phone_charger
      selector:
        entity:
          domain: switch

auto_manage:
  name: Auto Manage
  description: Evaluate the current status and control chargers according to the active plan.
  fields:
    entry_id:
      name: Entry ID
      description: Optional – required only when multiple Smart Charger entries exist.
      example: 1234567890abcdef1234567890abcdef
      selector:
        text:

load_model:
  name: Load / Reset Learning Model
  description: Load or reset the persisted Smart Charger learning model.
  fields:
    entry_id:
      name: Entry ID
      description: Optional – required only when multiple Smart Charger entries exist.
      example: 1234567890abcdef1234567890abcdef
      selector:
        text:
    action:
      name: Action
      description: Use `load` (default) or `reset` to clear stored data.
      example: reset
      selector:
        select:
          options:
            - load
            - reset
    profile_id:
      name: Profile ID
      description: Profile name (optional; leave empty with `reset` to clear all).
      example: "My Phone"
