name: Validate

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Download repo
        uses: "actions/checkout@v2"
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands